Repository WordPress/theme-check, pull requests merged in 2020-04, with the labels that each got.

#210 Add check for wp_body_open.
  checks/basic.php
Labels: needs testing

#227 Check if the theme is a copy of underscores
  checks/underscores.php
Labels: decision needed, needs testing

#226 Check for URLs to image sites with non GPL images
  checks/nongplsites.php
Labels: decision needed

#233 Check for theme_location and menu name
  checks/navmenu.php
Labels: needs testing

#248 Add phpcs config and checking to the plugin
  .gitattributes
  .gitignore
  .phpcs.xml.dist
  composer.json
  composer.lock
Labels: enhancement

#230 Add warnings for demo content files and phpcs
  checks/filenames.php
Labels: needs testing

#225 Add check for disallowed theme names
  checks/themename.php
Labels: needs testing
